spring.application.name=final-project-giuseppe
spring.datasource.url=jdbc:mysql://localhost:3306/progettoFinaleGiuseppe
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

supabase.url=https://szklbvwrltuhqzitdpuk.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6a2xidndybHR1aHF6aXRkcHVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk0OTA4OTksImV4cCI6MjEwNTA2Njg5OX0.SVRjpORbF3S1nYHRAqSoclL3QPmGvrEfOoztmMc3Rm8
supabase.bucket=/storage/v1/object/db1
supabase.image=/storage/v1/object/db1